version: "3.8"

services:
  postgres:
    image:  postgres:14.1-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password0701
      - POSTGRES_DB=practice
    ports:
      - '5475:5432/tcp'
    volumes:
      - postgres-storage:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data

  elastic_api:
    build: .
    container_name: elasticService
    ports:
      - '7575:7575'
volumes:
  postgres-storage:
  elastic-storage:
